#!/bin/bash
# Android App Build Guide - Quetzal GIS Studio

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  📱 QUETZAL GIS STUDIO - ANDROID APP BUILD GUIDE          ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

PROJECT_DIR="/Users/xavasena/hive/QuetzalGISStudio"

echo "📁 Project Location: $PROJECT_DIR"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔧 OPTION 1: Build Using Android Studio (RECOMMENDED)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Steps:"
echo "1. Open Android Studio"
echo "2. Click: File → Open → Select QuetzalGISStudio folder"
echo "3. Wait for Gradle sync to complete"
echo "4. Build menu: Build → Build Bundle(s)/APK(s) → Build APK(s)"
echo ""
echo "📱 Terminal shortcut:"
echo "   open -a 'Android Studio' $PROJECT_DIR"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⚙️  OPTION 2: Command Line Build (Requires Java/Android SDK)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Prerequisites:"
echo "   • Java Development Kit (JDK) 11+"
echo "   • Android SDK installed"
echo "   • ANDROID_HOME environment variable set"
echo ""

echo "✅ Build Commands:"
echo ""
echo "📦 Debug APK:"
echo "   cd $PROJECT_DIR"
echo "   ./gradlew assembleDebug"
echo "   # Output: app/build/outputs/apk/debug/app-debug.apk"
echo ""
echo "📦 Release APK:"
echo "   ./gradlew assembleRelease"
echo "   # Output: app/build/outputs/apk/release/app-release.apk"
echo ""
echo "🧪 Run on Emulator:"
echo "   ./gradlew installDebug"
echo "   # Or: adb install app/build/outputs/apk/debug/app-debug.apk"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 PROJECT STRUCTURE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
find "$PROJECT_DIR" -type f ! -path "*/build/*" -not -path "*/.*" | sort | sed 's|'$PROJECT_DIR'||g' | head -20
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎯 PROJECT FEATURES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Core Components:"
echo "   • MainActivity with 4-tab navigation (Map, Dashboard, Analysis, Settings)"
echo "   • GISAnalysisService for background terrain analysis"
echo "   • GISEngine with core GIS algorithms"
echo "   • Offline map support (Mapsforge)"
echo "   • SQLite database for local storage"
echo ""
echo "✅ Network Features:"
echo "   • Retrofit 2 + OkHttp for REST API"
echo "   • WebSocket for real-time updates"
echo "   • Backend: http://10.168.222.67:8000"
echo ""
echo "✅ Location & Maps:"
echo "   • GPS location services"
echo "   • Offline maps with Mapsforge"
echo "   • Real-time position tracking"
echo ""
echo "✅ Data Analysis:"
echo "   • Terrain elevation analysis"
echo "   • Data validation (LiDAR, Raster, Vector)"
echo "   • Multi-source data fusion"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 DEPLOYMENT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📲 Install on Physical Device:"
echo "   1. Enable USB Debugging on phone"
echo "   2. Connect via USB"
echo "   3. Run: adb install app/build/outputs/apk/debug/app-debug.apk"
echo ""
echo "📱 Install on Emulator:"
echo "   1. Create/start Android Virtual Device"
echo "   2. Run: adb install app/build/outputs/apk/debug/app-debug.apk"
echo ""
echo "🎯 Google Play Store (Future):"
echo "   1. Build release APK: ./gradlew assembleRelease"
echo "   2. Sign APK with keystore"
echo "   3. Upload to Google Play Console"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📖 CONFIGURATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔧 Backend Configuration:"
echo "   File: app/src/main/java/com/quetzal/gisstudio/utils/ApiClient.java"
echo "   Default: http://10.168.222.67:8000"
echo ""
echo "   To change backend URL:"
echo "   1. Edit ApiClient.java"
echo "   2. Update BASE_URL variable"
echo "   3. Rebuild APK"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ QUICK START"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎯 Fastest way to test:"
echo ""
echo "1️⃣  Open in Android Studio:"
echo "    open -a 'Android Studio' $PROJECT_DIR"
echo ""
echo "2️⃣  Let Gradle sync (5-10 minutes first time)"
echo ""
echo "3️⃣  Build & Run:"
echo "    • Click Run button (▶️)"
echo "    • Select emulator or device"
echo ""
echo "4️⃣  Test Features:"
echo "    • Open Map tab"
echo "    • View Dashboard with metrics"
echo "    • Run analysis on terrain data"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📚 DOCUMENTATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📖 Read these files for more info:"
echo "   • README.md - Project overview"
echo "   • ANDROID_BUILD_GUIDE.md - Detailed build instructions"
echo "   • app/build.gradle - Dependencies configuration"
echo "   • app/src/main/AndroidManifest.xml - Permissions & activities"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✨ Ready to build! 🚀"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
