#!/bin/bash
echo "=== Training Status Check ==="
echo ""
echo "📊 Recent Training Logs:"
docker exec hive-backend-1 tail -20 /workspace/training.log 2>/dev/null || echo "No logs yet"
echo ""
echo "💾 Saved Models:"
docker exec hive-backend-1 ls -lh /workspace/*.pt 2>/dev/null || echo "No models saved yet"
echo ""
echo "🔄 Container Status:"
docker ps --filter "name=hive-backend-1" --format "{{.Names}}: {{.Status}}"
echo ""
echo "⏰ Training started at:"
docker exec hive-backend-1 cat /workspace/training_status.log 2>/dev/null || echo "No start time logged"
