#!/bin/bash
# Quick guide to verify senasaitech.com in SendGrid

echo "📧 Domain Verification for senasaitech.com"
echo "=========================================="
echo ""
echo "This will make emails land in INBOX instead of Junk."
echo ""
echo "Step 1: Go to SendGrid Dashboard"
echo "  → https://app.sendgrid.com/"
echo ""
echo "Step 2: Navigate to Sender Authentication"
echo "  → Settings → Sender Authentication → Authenticate Your Domain"
echo ""
echo "Step 3: Enter Your Domain"
echo "  → Domain: senasaitech.com"
echo "  → Click 'Next'"
echo ""
echo "Step 4: Copy DNS Records"
echo "  SendGrid will show you DNS records to add:"
echo "  - CNAME records (3-4 records)"
echo "  - These add SPF, DKIM, and DMARC authentication"
echo ""
echo "Step 5: Add DNS Records to Your Domain"
echo "  → Go to your domain registrar (GoDaddy, Namecheap, etc.)"
echo "  → Add each CNAME record exactly as shown"
echo "  → Wait 24-48 hours for DNS propagation"
echo ""
echo "Step 6: Verify in SendGrid"
echo "  → Return to SendGrid → Click 'Verify'"
echo "  → Once verified, emails will land in inbox!"
echo ""
echo "✅ Benefits After Verification:"
echo "  - Emails go to INBOX (not junk)"
echo "  - No 'via sendgrid.net' warning"
echo "  - Higher deliverability rate"
echo "  - Professional sender reputation"
echo ""
echo "🚀 Quick Alternative (Immediate):"
echo "  1. Mark the test email as 'Not Junk' in your Live.com"
echo "  2. This trains the spam filter for future emails"
echo "  3. Then send to Mario - should land in inbox"
echo ""
read -p "Press Enter to open SendGrid dashboard..." 
open "https://app.sendgrid.com/settings/sender_auth"
